# Generated by Django 3.1.2 on 2020-11-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('telefone1', models.CharField(max_length=100, verbose_name='Telefone')),
                ('telefone2', models.CharField(max_length=100, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=250, verbose_name='E-mail')),
                ('skype', models.CharField(max_length=100, verbose_name='Link Skype')),
            ],
            options={
                'verbose_name': 'Informações de Contato',
                'verbose_name_plural': 'Informações de Contato',
            },
        ),
        migrations.CreateModel(
            name='PaginaIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('texto', models.TextField(max_length=400, verbose_name='Texto')),
                ('image', models.CharField(max_length=400, verbose_name='Url da Imagem')),
            ],
            options={
                'verbose_name': 'Itens Página Index',
                'verbose_name_plural': 'Itens Página Index',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo do Serviço')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('fa fa-street-view', 'Pessoa')], max_length=17, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
