# Generated by Django 3.1.2 on 2020-11-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='endereco',
            field=models.CharField(default=12000, max_length=200, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
