# Generated by Django 3.1.2 on 2020-11-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contato_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='active',
        ),
        migrations.RemoveField(
            model_name='paginaindex',
            name='active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='active',
        ),
    ]
