# Generated by Django 3.1.2 on 2020-10-15 00:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('datanasc', models.DateField(max_length=100, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('tel', models.CharField(max_length=100, verbose_name='Telefone')),
                ('religiao', models.CharField(max_length=100, verbose_name='Religião')),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteira(o)'), ('C', 'Casada (o)'), ('V', 'Viúva(o)'), ('E', 'Em União estável')], max_length=100, null=True, verbose_name='Estado civil')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço completo')),
                ('escolaridade', models.CharField(blank=True, choices=[('in', 'Infantil ou Jardim'), ('f1', 'Fundamental Incompleto'), ('f2', 'Fundamental Completo'), ('m1', 'Médio Incompleto'), ('m2', 'Médio Completo'), ('s1', 'Superior Incompleto'), ('s2', 'Superior Completo'), ('p', 'Pós Graduação'), ('me', 'Mestre'), ('d', 'Doutor'), ('pd', 'Pós Doutor')], max_length=100, null=True, verbose_name='Grau Escolaridade')),
                ('profissao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local que trabalha e função')),
                ('contato_recado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato para recado/emergencia - Nome e Telefone')),
                ('motivo_consulta', models.TextField(blank=True, max_length=255, null=True, verbose_name='Quais motivos levaram a buscar a terapia?')),
                ('outra_consulta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Realizou psicoterapia (com psicólogo) antes? Se sim, por quanto tempo?')),
                ('acompanhamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Realiza acompanhamento com médico psiquiatra atualmente? Se sim, há quanto tempo e qual o nome do(a) médico(a)?')),
                ('medicamento', models.TextField(blank=True, max_length=255, null=True, verbose_name='Faz uso de alguma medicação? Se sim, qual(is) e há quanto tempo? (Considere aquela de uso frequente ou contínuo, nome da medicação, a dosagem e quem prescreveu) ')),
                ('desejo', models.TextField(blank=True, max_length=255, null=True, verbose_name='O que deseja alcaçar com a psicoterapia?')),
                ('aumentar_comport', models.TextField(blank=True, max_length=255, null=True, verbose_name='Quais comportamentos deseja aumentar com a psicoterapia?')),
                ('diminuir_comport', models.TextField(blank=True, max_length=255, null=True, verbose_name='Quais comportamentos deseja diminuir com a psicoterapia?')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('dataconsulta', models.DateField(verbose_name='Data Consulta')),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Descrição do Atendimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario_paciente', to='prontuario.paciente')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
    ]
