# Generated by Django 3.1.2 on 2020-11-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Cadastro de Paciente', 'verbose_name_plural': 'Cadastro de Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='prontuario',
            options={'verbose_name': 'Cadastro de Consulta', 'verbose_name_plural': 'Cadastro de Consultas'},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastro do cliente criado em:'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastro do cliente criado em:'),
        ),
    ]
